import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

class AppIcons {
  AppIcons._();

  static const String overview = 'assets/icons/098visualization_99988.svg';
  static const String receipt = 'assets/icons/receipt.svg';
  static const String simcard = 'assets/icons/simcard_icon_241921.svg';
  static const String wallet = 'assets/icons/wallet_icon_242153.svg';
  static const String messages = 'assets/icons/messages_icon_241893.svg';
  static const String profileUser = 'assets/icons/profile_user.svg';
  static const String users = profileUser;
  static const String walletMoney = 'assets/icons/wallet_money_icon_242771.svg';
  static const String transaction = 'assets/icons/transaction.svg';
  static const String trendUp = 'assets/icons/trend_up_icon_242025.svg';
  static const String calendar = 'assets/icons/calendar_icon_183943.svg';
  static const String moneyRemove = 'assets/icons/money_remove_icon_241831.svg';
  static const String check = 'assets/icons/118check_99987.svg';
  static const String cross = 'assets/icons/cross.svg';
  static const String history = 'assets/icons/history_icon_155273.svg';
  static const String refresh = 'assets/icons/refresh_square_icon_242173.svg';
  static const String saveAdd = 'assets/icons/save_add_icon_241850.svg';
  static const String search = 'assets/icons/search_zoom_in_icon_242189.svg';
  static const String settings = 'assets/icons/setting_icon_241871.svg';
  static const String trash = 'assets/icons/trush_square_icon_242180.svg';
  static const String edit = 'assets/icons/101edit_99874.svg';
  static const String copy = 'assets/icons/copy.svg';
  static const String download = 'assets/icons/download_icon_184019.svg';
  static const String send = 'assets/icons/send.svg';
  static const String eye = 'assets/icons/eye_on_see_show_view_vision_watch_icon_123215.svg';
  static const String shield = 'assets/icons/shield_security_icon_242117.svg';
  static const String toggleOn = 'assets/icons/toggle_on_icon_242201.svg';
  static const String toggleOff = 'assets/icons/toggle_off_circle_icon_241985.svg';
  static const String twoFa = 'assets/icons/two_fa.svg';
  static const String info = 'assets/icons/info_square_icon_184028.svg';
  static const String warning = 'assets/icons/warning_icon_123234.svg';
  static const String logout = 'assets/icons/logout_icon_184025.svg';
  static const String walletAdd = 'assets/icons/wallet_add_icon_241828.svg';
  static const String moneyAdd = 'assets/icons/money_add_icon_242178.svg';
  static const String deposit = 'assets/icons/deposit.svg';
  static const String withdraw = 'assets/icons/withdraw.svg';
  static const String exchange = 'assets/icons/exchange-alt.svg';
  static const String transfer = 'assets/icons/transfer.svg';
  static const String billPay = 'assets/icons/bill_pay.svg';
  static const String fund = 'assets/icons/fund.svg';
  static const String staff = 'assets/icons/staff.svg';
  static const String agent = 'assets/icons/agent.svg';
  static const String tickCircle = 'assets/icons/tick_circle_icon_241974.svg';
  static const String cancelCircle = 'assets/icons/cancel_circle.svg';
  static const String minusSquare = 'assets/icons/minus_square_icon_242092.svg';
  static const String note = 'assets/icons/note_icon_241852.svg';
  static const String noteAdd = 'assets/icons/note_add_icon_242058.svg';
  static const String lock = 'assets/icons/lock_icon.svg';
  static const String unlock = 'assets/icons/unlock_icon.svg';
  static const String fingerprint = 'assets/icons/finger_print.svg';
  static const String faceId = 'assets/icons/face_id.svg';
  static const String language = 'assets/icons/language_121815.svg';
  static const String moon = 'assets/icons/moon_dark_mode.svg';
  static const String sun = 'assets/icons/sun-sunny.svg';
  static const String menu = 'assets/icons/menu.svg';
  static const String moreCircle = 'assets/icons/more_circle_icon_242163.svg';
  static const String userEdit = 'assets/icons/user_edit_icon_241980.svg';
  static const String userMinus = 'assets/icons/user_minus_icon_242055.svg';
  static const String userTag = 'assets/icons/user_tag_icon_242137.svg';
  static const String email = 'assets/icons/email-envelope-mail.svg';
  static const String mail = 'assets/icons/mail-01.svg';
  static const String phone = 'assets/icons/Phone-cal.svg';
  static const String personalCard = 'assets/icons/personalcard.svg';
  static const String passport = 'assets/icons/passport.svg';
  static const String id = 'assets/icons/id_90968.svg';
  static const String location = 'assets/icons/location-map.svg';
  static const String building = 'assets/icons/building_business_home_house_mobile_navigation_office_icon_123210.svg';
  static const String bank = 'assets/icons/building_bank_link_regular_icon_205561.svg';
  static const String coin = 'assets/icons/coinicon_114542.svg';
  static const String virtualCard = 'assets/icons/virtual_card.svg';
  static const String stripe = 'assets/icons/stripe_logo_icon.svg';
  static const String usdCoin = 'assets/icons/usd_coin_usdc.svg';
  static const String gift = 'assets/icons/my_gift.svg';
  static const String buyGift = 'assets/icons/buy_gift.svg';
  static const String shoppingBag = 'assets/icons/shopping_bag_icon_242106.svg';
  static const String tag = 'assets/icons/tag_icon_242166.svg';
  static const String task = 'assets/icons/task_icon_242198.svg';
  static const String taskSquare = 'assets/icons/task_square_icon_241875.svg';
  static const String notification = 'assets/icons/notification_icon_241984.svg';
  static const String security = 'assets/icons/security_icon_241960.svg';
  static const String securityCard = 'assets/icons/security_card_icon_242000.svg';
  static const String securitySafe = 'assets/icons/security_safe_icon_241889.svg';
  static const String radar = 'assets/icons/radar_icon_241825.svg';
  static const String scan = 'assets/icons/scan_icon_242001.svg';
  static const String scanning = 'assets/icons/scanning_icon_241836.svg';
  static const String wifi = 'assets/icons/wifi_icon_242024.svg';
  static const String smartHome = 'assets/icons/smart_home_icon_241309.svg';
  static const String routeSquare = 'assets/icons/route_square_icon_241822.svg';
  static const String webLiveChat = 'assets/icons/web_live_chat_icon.svg';
  static const String receive = 'assets/icons/receive.svg';
  static const String remittance = 'assets/icons/remittance.svg';
  static const String receiptEdit = 'assets/icons/receipt_edit.svg';
  static const String moneyChange = 'assets/icons/money_change_icon_242160.svg';
  static const String moneys = 'assets/icons/moneys_icon_242132.svg';
  static const String question = 'assets/icons/question.svg';
  static const String loading = 'assets/icons/loading_icon_149916.svg';
  static const String zip = 'assets/icons/zip-file-r.svg';
  static const String database = 'assets/icons/save_icon_242042.svg';
  static const String backup = 'assets/icons/save_add_icon_241850.svg';
  static const String statusUp = 'assets/icons/status_up_icon_242088.svg';
  static const String trendDown = 'assets/icons/trend_down_icon_241863.svg';
  static const String messageText = 'assets/icons/message_text.svg';
  static const String messageTick = 'assets/icons/message_tick_icon_242040.svg';
  static const String messageTime = 'assets/icons/message_time_icon_242067.svg';
  static const String verify = 'assets/icons/verify_icon_241982.svg';
  static const String details = 'assets/icons/details.svg';
  static const String userIdentification = 'assets/icons/user_identification.svg';
  static const String receiptCheck = 'assets/icons/118check_99987.svg';
  static const String hourglass = 'assets/icons/timer_start_icon_242184.svg';
  static const String paperclip = 'assets/icons/paperclip_icon_242053.svg';
  static const String person = 'assets/icons/profile_user.svg';
  static const String eyeOff = 'assets/icons/eye_hide_off_see_view_vision_watch_icon_123214.svg';
  static const String eyeOn = 'assets/icons/eye_on_see_show_view_vision_watch_icon_123215.svg';
  static const String arrowBack = 'assets/icons/rightArrow.svg';
  static const String rightArrow = 'assets/icons/rightArrow.svg';
  static const String calendarDay = 'assets/icons/calendar_day.svg';
  static const String cloudOff = 'assets/icons/warning_icon_123234.svg';
  static const String map = 'assets/icons/location-map.svg';
  static const String flag = 'assets/icons/passport.svg';
  static const String speed = 'assets/icons/radar_icon_241825.svg';
  static const String cellular = 'assets/icons/simcard_icon_241921.svg';
  static const String loop = 'assets/icons/repeate_one.svg';
  static const String category = 'assets/icons/task_square_icon_241875.svg';
  static const String playCircle = 'assets/icons/smart_home_icon_241309.svg';
  static const String voice = 'assets/icons/voice_square_icon_242071.svg';
  static const String dropDown = 'assets/icons/rightArrow.svg';

  static Widget svg(String path, {double size = 24, Color? color, bool flipX = false, double? rotate}) {
    Widget w = SvgPicture.asset(path, width: size, height: size, colorFilter: color != null ? ColorFilter.mode(color, BlendMode.srcIn) : null);
    if (flipX) w = Transform.scale(scaleX: -1, child: w);
    if (rotate != null) w = Transform.rotate(angle: rotate, child: w);
    return w;
  }

  static Widget icon(String path, {double size = 24, Color? color}) => svg(path, size: size, color: color);
}
